services:


  web:
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - API_REDIS_HOST=redis
    ports:
      - 8000:8000
    depends_on:
      - redis
    
    command: ["uvicorn", "web:app", '--host', '0.0.0.0', '--port', '8000']
  
  redis:
    image: redis:alpine
    container_name: redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 6379:6379

  tg_bot:
    build:
      context: ./tg_bot
      dockerfile: Dockerfile
    env_file:
    - .env
    depends_on:
      - web
    command: ['python3', 'bot.py']

  nginx:
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - 8082:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d



